apiVersion: v1
kind: Service
metadata:
  name: flink-jobmanager
spec:
  ports:
  - name: rpc
    port: 6123
    # nodePort: 6123
  - name: blob
    port: 6124
    # nodePort: 6124
  - name: query
    port: 6125
    # nodePort: 6125
  - name: ui
    port: 8081
    nodePort: 30000
  type: NodePort
  selector:
    app: flink
    component: jobmanager

